### PR TITLE
feat: Update `container-structure-test` to 1.14.0 (#2)

### PR DESCRIPTION
**Pull request by MaxymVlasov**
To use renovate, after merge PR, do next
> Activate [Renovatebot Github App](https://github.com/marketplace/renovate) for your repo or ask your GitHub org administrators to enable it.

### CODE REVIEW

**Comment by jpreese** [comment]
Thanks for the PR! The version updates make sense to me, but I'm not quite sold on renovate. The release cadence isn't that frequent and people are more than welcome to create PRs if they need something newer.

If this is something we're still interested in pursuing, could these features be split into different PRs to have a better discussion?

**Comment by MaxymVlasov** [comment]
Sure. Let me remove Renovate from this PR. And, In case you'll see reason on deps auto-updates - feel free to just copy my changes.

**Comment by MaxymVlasov** [comment]
@jpreese ?

**Comment by jpreese** [comment]
Sorry @MaxymVlasov, completely forgot about this. Working on the release now.

**Pull request merged**
